before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: pntrJdbgJw+9EA3Ono+w2fv+VVDspKDFnMumG+vJAV5fyqHzQJhnkFyF7rwSIvBVE2AjKbhJnHdW41+pe3TObtlS5QnLznmhq1aTOagbp1XDcNyUXrwtmjH28Q7p+wIWbehHpJ6kCK5T4SHJE8D1XaIoBadr6qlNazWEFraJ85JCMNc7Sy886QzxTHPzGdDD6fFZATUShTnc2XXyGLq7cCJIKFstjipyYRerrgJ3Q/KQmTpdojkrsA02gjBSfbNw6ZVTx6+E/jYMnJDWWlA87TriSQOheKxXCTH3Bae0VvsQ/W3cDmoLOLqXlkxijXOpeIxJylAbFnAjQ4DiUA8mNvftvS+maCC/S0GJEkHfe4DRTh/0de2CDUITjLDA4xg9tNy/9YDJK4rve6WIFNgR4FFSpdEMvGsPv4ghPUFm7itdoQaHLHB+Ac6A9pHIAcJrDqtCVAVLamg3Bc0jjizQUyxQLiULI1De4M3tXinxLzFevL+ZaSHy0bBV/4R8+A+aEnrUDOQa1JckJmzxeTE4lBggojvO19yzt2dehJfh0Fgm/F5QjoP/oHr6Mh5Itgd4gBVtFTwji5mVFYiCTubPW1O2aBFaYxlnsl8dxh0ccBq8gzq1qH0tMqEa9RCansxVlXrxEivURCiFrglSf1ej2jzwydAEnhAzEGiTZOC14g0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
